### ISSUE TITLE
Is this really working ?

### ISSUE THREAD

**Issue by SPINACHCEO** [Unity-Technologies/EditorVR#1]
Well I cannot see a project structure in this repo it seems like there is only contents of Assets folder has been committed. But since I see those .meta files is here I guess there's no problem so I imported into an empty project. 

But soon I get 120 of missing assembly reference errors, does anyone have a chance to work it out ?

**Comment by MrQ89** [comment]
Hey, you need to use a special Unity version and the Unitypackage in releases.
You can get more info in the blogpost about EditorVR
[https://blogs.unity3d.com/2016/12/15/editorvr-experimental-build-available-today/](url)

**Comment by amirebrahimi** [comment]
There will be more info to come in the form of a readme, but for now, you will need to clone and check out dev/main (not master) for this to work and grab subrepos. So, create a new project first and then clone this from your Assets directory:

cd Assets
`git` lfs clone --recursive -b dev/main https://github.com/Unity-Technologies/EditorVR
cd EditorVR
git submodule update`
