### ISSUE TITLE
Locked Objects Workspace

### ISSUE THREAD

**Issue by amirebrahimi** [Unity-Technologies/EditorVR#108]
With the improvement to locking (#107) there is now a new Locked Objects Workspace to make it easier to see what objects are locked in the scene. You can still use the Hierarchy Workspace and filter for Locked objects as well.

**Comment by timoni** [comment]
Changes: 
- Change icon from lock to unlock if ray hovers over the icon
- Use outline shader on related object when hovering over locked object list item in the workspace
- Include Dylan's work around radial lock pulsing--can't tell that you can unlock an object now onhover
