### ISSUE TITLE
Highlight looks incorrect in MiniWorld

### ISSUE THREAD

**Issue by amirebrahimi** [Unity-Technologies/EditorVR#113]
Happens in 0.0.3

If an object is being hovered with the ray, it shows an odd looking highlight in the MiniWorld.

**Comment by mtschoen-unity** [comment]
This is because of the CustomClipPlanes shader. I see a couple of options:
* Don't show highlights in MiniWorld
* Create a custom clipped version of the highlight shader and draw highlights explicitly in MiniWorld
* Find a better way to "inject" clip code into existing shaders
