### ISSUE TITLE
Replace/remove Unity's skeletal mesh overlay on selected objects

### ISSUE THREAD

**Issue by timoni** [Unity-Technologies/EditorVR#119]
- Remove it entirely for ray-selected objects (the gizmo is enough)
- For direct selection, simply keep the outline from the hover state.

**Comment by mtschoen-unity** [comment]
Let me describe an example, for clarity:

1. I ray-hover an object; The outline appears
2. I pull the trigger, selecting the object; Manipulator appears at pivot/center, outline disappears
3. With the object selected, I dip the cone into it; Manipulator disappears and hover re-appears
4. I pull the trigger and direct manipulate the object; Outline re-appears
5. I release the trigger; Outline stays
6. I pull the cone outside of the object; Outline disappears, manipulator re-appears
7. I ray-hover the object; Nothing happens (aside from manipulator hover states)

In another example:
1. I ray-hover an object; The outline appears
2. I dip the cone into the object; The outline stays
3. I pull the trigger to select the object and start manipulating; The outline stays
4. I release the trigger; The outline stays
5. I pull the cone out, while still pointing the ray at the object; The outline stays
6. I point the ray away from the object; The outline disappears

Is this correct? If so, I have two concerns: 
1. I'm not sure the manipulator will be enough to indicate the selected object. For a number of objects with pivots in the same spot, it would be impossible to know what is selected just by looking (think: previously selected object when EVR starts, or I selected it a while ago and forgot)
2. I would like to incorporate Jono's feedback about visual feedback for direct manipulation. Some materials may not intersect properly with the cone, and even with normal materials, sometimes really small objects or objects with strange geometry will intersect at unpredictable times. I would like to have something like a different color outline to differentiate between ray and direct hovers.
