### ISSUE TITLE
Keyboard has wrong scale + object position are incorrect (Inspector)

### ISSUE THREAD

**Issue by sarahhockman** [Unity-Technologies/EditorVR#129]
**#125, Using EVR-staging, pulled 4/4/17, [Alien Planet Asset Pack](https://www.assetstore.unity3d.com/en/#!/content/74011), Oculus**

I noticed some issues when using the Inspector workspace.

To begin with, when I have an object selected and the Inspector open, I attempt to open the keyboard, and at first it appeared off to the side, out of view, then when I closed/reopened the workspace and select a value to prompt the keyboard, it appears clustered (seen in gif below), and cannot be closed.

![ezgif com-crop 8](https://cloud.githubusercontent.com/assets/25187040/24671179/84a293e6-1925-11e7-8a36-cd2d86f30063.gif)

Additionally, when an object was selected, the Inspector indicated that the Local Position (Y) was continuously changing, even though I was not manipulating the object and it did not visibly appear to be moving. I noticed this again in the (Z) position when attempting to replicate.

![ezgif com-crop 9](https://cloud.githubusercontent.com/assets/25187040/24671825/d1c4066c-1927-11e7-914d-f80d83dda843.gif)
(Difficult to see in gif; can additionally view in video file [here.](https://drive.google.com/a/unity3d.com/file/d/0B25RksN0ueScQklaSzQyRlk2VGM/view?usp=sharing)) 

I was able to replicate this instance by:
1) Open Inspector and select an object
2) Prompt the keyboard (appears behind workspace, out of view)
3) Close workspace and reopen (cannot close keyboard), select object
4) Local Position (Y or Z in my case) of object continuously changes (when I am not moving the object)

Also, the Console is flooded with errors, such as: 

* GetObject failed to find Object for Library Representation

* NullReferenceException: Object reference not set to an instance of an object
UnityEditor.Experimental.EditorVR.UI.InputField+<MoveKeyboardToInputField>c__Iterator2C.MoveNext () (at Assets/EditorVR/Scripts/UI/InputField.cs:149)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
UnityEditor.Experimental.EditorVR.Core.EditorVR:Update()

* NullReferenceException: Object reference not set to an instance of an object
UnityEditor.Experimental.EditorVR.UI.KeyboardButton.OnHandleHoverStarted (UnityEditor.Experimental.EditorVR.Handles.HandleEventData eventData) (at Assets/EditorVR/Scripts/Handles/UI/KeyboardButton.cs:218)
UnityEditor.Experimental.EditorVR.Handles.BaseHandle.OnRayEnter (UnityEditor.Experimental.EditorVR.Modules.RayEventData eventData) (at Assets/EditorVR/Scripts/Handles/BaseHandle.cs:119)
UnityEditor.Experimental.EditorVR.Modules.ExecuteRayEvents.Execute (IRayEnterHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at Assets/EditorVR/Scripts/Modules/MultipleRayInputModule/ExecuteRayEvents.cs:43)
UnityEngine.EventSystems.ExecuteEvents.Execute[IRayEnterHandler] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.EventFunction`1 functor) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:269)
UnityEditor.Experimental.EditorVR.Core.EditorVR:Update()

[Will investigate this further and add as needed.]

**Comment by mtschoen-unity** [comment]
I am able to reproduce this and I'm looking into it.
