### ISSUE TITLE
Clicking the thumb pad during dragging free selection sphere causes odd behavior

### ISSUE THREAD

**Issue by NavidNikbin** [Unity-Technologies/EditorVR#135]
Selecting a GameObject, then starting to drag free selection sphere and clicking the thumb pad while dragging, deselects the GameObject. Afterward it is not possible to select the GameObject with the same controller. By selecting the GameObject with the other controller, only the free selection sphere will appear (other parts of the manipulator gizmo will become hidden). In this situation, dragging the free selection sphere with the second controller causes the GameObject to move toward the first controller's ray and be manipulated by the first controller (while the trigger of the second controller is pressed).

**Comment by amirebrahimi** [comment]
@NavidNikbin - is this a regression that you are reporting off of our staging branch (0.0.4) or is this from a current or previous release?

**Comment by NavidNikbin** [comment]
@amirebrahimi - I used EditorVR-0-0.0.3/HTC Vive/Unity Version 5.4.3xEditorVR-p3
