### ISSUE TITLE
Undesirable behavior when starting with Rift on desk

### ISSUE THREAD

**Issue by mtschoen-unity** [Unity-Technologies/EditorVR#136]
I might have to calibrate my tracking, but in my environment, the tracking center always starts at the HMD position. Thus, if I close EVR with the HMD on my head, and then start it up with it on the desk, my saved camera rig and workspace positions are not reachable.

**Comment by amirebrahimi** [comment]
Well, this makes sense then because it would be expected that you would end with it on your desk, too, or vice versa, starting with it on your head?

**Comment by mtschoen-unity** [comment]
I would expect the position to be loaded when I put on the HMD. I don't think we currently have access to an event when the sensor detects that the HMD is on the head, but from a UX perspective, that is how I would want this to work.
