### ISSUE TITLE
Cannot grab yourself in the MiniWorld

### ISSUE THREAD

**Issue by NavidNikbin** [Unity-Technologies/EditorVR#147]
In 0.0.3 you could grab yourself in MiniWorld to move yourself. It seems it is not working in 0.0.4
Tested with EditorVR 0.0.4 unity package + HTC Vive

**Comment by mtschoen-unity** [comment]
You're right, this is a regression in 0.0.4. There is a fix in review currently. If you need this urgently, pull bugfixes/amir/hotfix-fix. If you're curious, check out #142
