### ISSUE TITLE
Can scroll a single line of files in ProjectWorkspace off of the screen

### ISSUE THREAD

**Issue by amirebrahimi** [Unity-Technologies/EditorVR#149]
Repro:
1. Select a folder where there is only one line of objects on the right side of the divider.
2. Scroll those objects off of the view.
3. Notice that they don't bounce back.

**Comment by dunity** [comment]
This bug/issue is still present.

**Comment by AndrewTHEManeri** [comment]
Fixed thanks to @stella3d
