### ISSUE TITLE
Re-scaling the world: Icon (size reference) draws under the items in the Miniworld

### ISSUE THREAD

**Issue by sarahhockman** [Unity-Technologies/EditorVR#159]
**Using EVR-staging[0.0.5], 4/21/17 [#150]**

Also not a huge issue, but one to note:

When the Miniworld workspace is open and I opt to re-scale the world, the
icon image (size reference) draws under the items in the Miniworld workspace.

![ezgif com-video-to-gif 5](https://cloud.githubusercontent.com/assets/25187040/25292397/c92a8c2c-268a-11e7-8f03-d782d8ab8def.gif)

Similarly as above, more of an aesthetic issue that would not not an issue that would effect functionality. But would be a useful fix for the purpose of screen-caps and demos.

**Comment by dunity** [comment]
Fixed.  Closing issue.
