### ISSUE TITLE
UI of Tools in front of Workspaces

### ISSUE THREAD

**Issue by NavidNikbin** [Unity-Technologies/EditorVR#160]
When a Tool's UI is in front of a Workspace (for example Primitive Tool's UI in front of Project Workspace), the UI elements of the Tool will become blurred and almost transparent and UI texts will be unreadable. (Perhaps it is by design to prevent the occlusion of Workspaces, but I think it is not good)

![1](https://cloud.githubusercontent.com/assets/9757458/25310913/357a9c8e-27a6-11e7-9849-680021d41ec4.jpg)

**Comment by dunity** [comment]
This bug has been addressed.  Closing issue.

**Comment by NavidNikbin** [comment]
Thanks @dunity
