### ISSUE TITLE
design query: Nested vs Modules

### ISSUE THREAD

**Issue by leith-bartrich** [Unity-Technologies/EditorVR#163]
I'm digging through the EditorVR Awake method and I've noticed you have two types of objects being used as "modules" or "systems."  You have objects that inherit from "Nested" and then also MonoBehavior modules you add explicitly.

"Nested" objects are EditorVR specific.  They require a reference to EditorVR and therefore can't be used by other EditingContexts.  They are instantiated via Activator, which is a typical reflection based instantiation.  You get them by scanning the loaded assemblies, which is a common reflection based plugin solution.  I get that part.

MonoBehavior based modules don't necessarily depend on EditorVR.  Though I'm sure if I go through them one by one, some will.  They are explicitly added in the Awake method.

What is the intended difference between the two? Is there some kind of overhead you are trying to avoid by using a "Nested" object rather than a MonoBehavior?  Is there a logic at work as to which system you'd implement as Nested versus as a MonoBehavior?

**Comment by amirebrahimi** [comment]
Took awhile to get back to you on this one, @leith-bartrich. A Nested module is simply a module that couldn't be split out enough from EditorVR because of too many inter-dependencies. An actual Module (MonoBehaviour) is something that we see could be standalone and used for other purposes with clear dependencies outline through interfaces that may be used or public delegate properties that are exposed that require pairing up to implementations.

Was that helpful towards answering your question?

**Comment by leith-bartrich** [comment]
There seems to be a whole bunch of different things mixed up in here then if the principal differentiation is one of being inter-dependent versus decoupled.

If "Nested" means "inter-dependent," then it's odd that it is inherently instantiated via a plug-in architecture.  One would think that should be split out.  The two actually seem somewhat contradictory.  The parent shouldn't depend on a plugin as the plugin might not be there.

Further, if it's a plug-in, it's odd that it doesn't receive Unity styled Messages.  It's not a Behavior, so it will not receive them automatically as a Behavior would.  One would think the "Message" system would be a great boon to a plug-in system architecture.

Lastly, the static reference in Nested, to the parent, breaks the "dependency injection" design pattern referenced here:

https://docs.google.com/document/d/1EGi9hKXAujfBMI2spErojdqRc0giqEnOu0NpwgBxtpg/edit

specifically, it's dependent on a static reference held outside the unit.  Which makes it inherently not unit testable (strictly speaking).  You can't inject a testbed object differently from instance to instance, unless you commit to testing them serially and changing the static reference before each run.  While this can often be assumed, it's technically not in the spirit of injection and unit testing.

I might take a crack at this in the next day or so.

I think the inter-dependence issues can probably be solved via abstraction and base classes.  And I think some of this can be split out to interfaces such as "INestable<T>" and "INestablePlugin<T>" and "INestableParent"  And further, with some NestableExtensions.  I'll see if I can untangle this cleanly and might submit a pull request shortly.  Will see.

**Comment by amirebrahimi** [comment]
@leith-bartrich, the only criteria at the time we split apart EditorVR.cs was simply to reduce the length and complexity of that source file. Anything that was easily converted into a module was converted and anything remaining was simply split out into partial class files for maintainability. Seeing as you're looking at the internals of EditorVR, which is not part of the API -- there wasn't a requirement for having a plug-in architecture or being unit testable. All good things, but wasn't the priority at the time. Hope that clarifies the intent.

Happy to take a look at a PR if you want to submit one. If there aren't any further queries, then I'll leave it to you to close the issue.

**Comment by leith-bartrich** [comment]
Moving on.
