### ISSUE TITLE
Moving objects in MiniWorld then pressing the trigger

### ISSUE THREAD

**Issue by StackBuilderVR** [Unity-Technologies/EditorVR#167]
Moving objects in MiniWorld, then pressing the trigger (to select other objects in the main world, deselecting all objects, ...) causes the first object that is moved in MiniWorld to disappear. In fact the scale of the first moved object will become (0, 0, 0). In addition, the trigger of the controller which moved the objects will become disabled.

I experienced this issue in 0.0.5 using HTC Vive.

**Comment by mtschoen-unity** [comment]
I can reproduce this on development. I see a NullReferenceException at EditorVR.MiniWorlds.cs:332. Do you see this, as well?

**Comment by StackBuilderVR** [comment]
Yes. The same exception at the same line.

**Comment by mtschoen-unity** [comment]
Thanks for your reply. This issue has been fixed and is under review. I also took the liberty to improve the interaction a little bit--all interactions now maintain the original scale of the object, and generally the code is a little cleaner and less dependent on other systems.

**Comment by StackBuilderVR** [comment]
Thanks for quick fix and improvements!
