### ISSUE TITLE
Improve locomotion to allow for change in Z

### ISSUE THREAD

**Issue by amirebrahimi** [Unity-Technologies/EditorVR#17]
Feedback from user:
Most of the movement system seemed to focus on X/Y movement which made it hard as I like to use a lot Z Movement when moving around. The teleportation system worked however teleportation is not very precise/immersive. I found it very useful to cross long distances but again it was only on the X/Y Plane. If the Teleporter was directional rather than a typical arc teleporter I think I would find it more useful. That way I could teleport up and Down by pointing in that direction.
There is a movement system on the asset store we use quite a bit for navigating around in 3D space. The Rubber band movement works like a 3D Joystick allowing control your velocity quite precisely. They also have a flight system that uses the rotation of the controller to move around. I would take a look at it to see what you think.

**Comment by koreldan** [comment]
yep, like google earth VR

**Comment by mtschoen-unity** [comment]
The current approach is to simply add up/down control to the right hand's "joystick locomotion." You will continue to rotate with horizontal input on both hands, but the left hand's vertical input will move you forward/back, while the right hand will move you up/down.
