### ISSUE TITLE
Unable to Select Objects (via Ray or Directly) After Drawing Primitives 

### ISSUE THREAD

**Issue by sarahhockman** [Unity-Technologies/EditorVR#179]
**[Using EVR-staging #177 , pulled 5/10/17, using VIVE]**

When placing assets and drawing primitives in a scene, I noticed that after opening the Primitive tool, drawing/placing primitives, then closing the tool (and no objects are selected), I am unable to select objects (both directly and via the ray). 

Additionally, I opened the project menu and tested placing Assets, which could initially be selected and manipulated, but after being placed and de-selected, they also could not be selected again or highlighted (directly or with the ray).

The only way to highlight/select and manipulate objects after this instance was by prompting them from the hierarchy. 

_**Note: this instance only occurred during a single session and could be resolved by exiting then re-opening EVR; but could be replicated.**_ 

Replicate this instance by:
1) Open the Primitive tool
2) Draw primitives in the scene
3) Exit out of the Primitive tool
4) Attempt to select the primitives that have just been placed

The instance can be seen in gifs below: 

![ezgif com-video-to-gif 6](https://cloud.githubusercontent.com/assets/25187040/25963200/520693ba-3635-11e7-8036-b69c9237eee3.gif)
![ezgif com-video-to-gif 7](https://cloud.githubusercontent.com/assets/25187040/25963207/55e44fea-3635-11e7-9aab-ddca3c6d148c.gif)
![ezgif com-video-to-gif 8](https://cloud.githubusercontent.com/assets/25187040/25963210/57eccb46-3635-11e7-9c85-1276da52f982.gif)

You can also reference the original video file **[here](https://drive.google.com/file/d/0B25RksN0ueScNVE5SmVFS08xSXM/view?usp=sharing)**.

**Comment by sarahhockman** [comment]
**Update:** 

 You can reference a video replicating the issue **[here](https://drive.google.com/file/d/0B25RksN0ueScelZHeDF3OEF4OFU/view?usp=sharing)**

I refreshed and made a new, empty project with a fresh pull of `EVR-staging` and attempted to repo.

It seems a bit tricky to replicate immediately, but I may have found what is causing the selection issue.

When I exit the Primitive tool  via the [X] button, the selection issue persists, and no objects can be highlighted or selected unless done so from the hierarchy or relaunch EVR.

However, when I prompt to exit the Primitive tool by: from the tool, select Menu button>click on "Primitives" to close the tool, I experience no selection issues.


Also, the following errors appear in the console:
```
IndexOutOfRangeException: Array index is out of range.
BoundsOctreeNode`1[UnityEngine.Renderer].ShrinkIfPossible (Single minLength) (at Assets/EditorVR/libs/UnityOctree/Scripts/BoundsOctreeNode.cs:333)
BoundsOctree`1[UnityEngine.Renderer].Shrink () (at Assets/EditorVR/libs/UnityOctree/Scripts/BoundsOctree.cs:270)
BoundsOctree`1[UnityEngine.Renderer].Remove (UnityEngine.Renderer obj) (at Assets/EditorVR/libs/UnityOctree/Scripts/BoundsOctree.cs:94)
UnityEditor.Experimental.EditorVR.Data.SpatialHash`1[UnityEngine.Renderer].RemoveObject (UnityEngine.Renderer obj) (at Assets/EditorVR/Scripts/Data/SpatialHash.cs:38)
UnityEditor.Experimental.EditorVR.Modules.SpatialHashModule+<UpdateDynamicObjects>c__Iterator0.MoveNext () (at Assets/EditorVR/Scripts/Modules/SpatialHashModule.cs:69)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
```
```
PlayerSettings Validation: Requested build target group (16) doesn't exist; #define symbols for scripting won't be added.
UnityEditor.PlayerSettings:SetScriptingDefineSymbolsForGroup(BuildTargetGroup, String)
UnityStandardAssets.CrossPlatformInput.Inspector.CrossPlatformInitialize:SetEnabled(String, Boolean, Boolean) (at Assets/Alien_planet/Editor/CrossPlatformInput/CrossPlatformInputInitialize.cs:136)
UnityStandardAssets.CrossPlatformInput.Inspector.CrossPlatformInitialize:.cctor() (at Assets/Alien_planet/Editor/CrossPlatformInput/CrossPlatformInputInitialize.cs:21)
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes()
```

**Comment by amirebrahimi** [comment]
@sarahhockman, I think @mtschoen-unity said that you verified this was fixed. I'll leave it to you to close this issue if that is the case.
