### ISSUE TITLE
Virtual 'F' key (frame object)

### ISSUE THREAD

**Issue by amirebrahimi** [Unity-Technologies/EditorVR#18]
Feedback from user:
Scaling and Object selection worked fantastically. I was able to pick up and manipulate objects with ease. The 3D gizmos for selection took a little to get use to however it did not take me long to get the hang of it. It was quite an incredible feeling when you picked up a 3D object and you got to place it in the VR world. The idea of having a tip on the controller in which to pick objects works great; I do wish I had the ability however pull myself to an object for selecting sort of like the F Key works now.
Additionally I was unsure when I had picked an object the radial menu that appeared on the controller was helpful but the animation I think got in the way either speed it up or make it instant a visual change could also alter the controller visuals similar to how Oculus Medium changes when you pick a new tool.

**Comment by timoni** [comment]
User should remain on ground plane unless selected object is:

- more than 7' above ground plane
- below ground plane.

 In these cases, the user should be positioned such that the object is  14-18" below HMD height.

**Comment by mtschoen-unity** [comment]
We punted on handling an intelligent offset, and instead place the center of the object directly in the center of the field of view, with an XY offset based on object bounds.

Resolved in #68

**Comment by mtschoen-unity** [comment]
We punted on handling an intelligent offset, and instead place the center of the object directly in the center of the field of view, with an XY offset based on object bounds.

Resolved in #68
