### ISSUE TITLE
[With Single Pass Enabled] “Miniworld -- Not Currently Working…” Tooltip Draws Underneath Menu Outline

### ISSUE THREAD

**Issue by sarahhockman** [Unity-Technologies/EditorVR#187]
**Using EVR-staging [0.0.7] #183 | Oculus | 17 May 2017**

**[With Single Pass Enabled]** 

While not an issue that would cause any disruption to workflow, I did notice that from the Main Menu, the Tooltip that appears over the Miniworld that describes “Not currently working in single pass” draws underneath the Main Menu outline. 

Can be seen in gif below:

![ezgif com-video-to-gif 9](https://cloud.githubusercontent.com/assets/25187040/26174098/13b5845e-3b03-11e7-8dc7-e4a8932cc880.gif)

Again, this is an aesthetic issue that would not disrupt workflow, but to note.

**Comment by amirebrahimi** [comment]
@sarahhockman - Can you verify if this is fixed now in the staging branched. I merged back @mtschoen-unity's changes
