### ISSUE TITLE
[Inspector] Cannot Close Lists within Inspector Workspace 

### ISSUE THREAD

**Issue by sarahhockman** [Unity-Technologies/EditorVR#188]
**Using EVR-staging [0.0.7] #183 | Oculus + VIVE | 17 May 2017**

When working with the Inspector workspace, I noticed that some of the lists that can be prompted will not close.

I first noticed this when I accidentally prompted the ‘Cast Shadows’ list when typing in the keyboard. When I try to exit this this via the [X], the button does not work -- and instead opens the preceding list “Motion Vectors”. 

After the above instance, the “Motion Vectors” list will close but the “Cast Shadows” list will not. 

Can be seen in gifs  below: 

![ezgif com-optimize 5](https://cloud.githubusercontent.com/assets/25187040/26174023/c7473540-3b02-11e7-83f2-637b3dbf0328.gif)

![ezgif com-video-to-gif 13](https://cloud.githubusercontent.com/assets/25187040/26173364/658fc102-3b00-11e7-9a01-641f3748fdc4.gif)

This instance occurred again when prompting the ‘Tag” List, which had the same issue as noted above, and could not be closed from the [X] button.

This issue could be resolved by closing the Inspector then re-opening the workspace, but could be replicated on my end by prompting each list and attempting to close them with the [X]. 

The lists that frequently could not be closed were “Cast Shadows” and “Tag”. 
“Layer” and “Motion Vectors” list seemed to close regularly.

**Comment by mtschoen-unity** [comment]
This is the result of a bug in the UI system, which is sorting these elements based on hierarchy order rather than raycast distance. I've started a conversation with Phillip which we will continue tomorrow morning.
