### ISSUE TITLE
[Inspector] User is Able to Select and Drag Face Values from Inspector Workspace

### ISSUE THREAD

**Issue by sarahhockman** [Unity-Technologies/EditorVR#189]
**Using EVR-staging [0.0.7] #183 | VIVE | 17 May 2017**

When working with the inspector, I noticed that I am able to select faces of values (such as the bar of X, Y, and  Z values from Local Rotation/Position/Scale), or the individual white plane containing the values.

I am also able to select the name blocks of other certain items in the inspector workspace (such as Mesh [name], Element [“”], Probe Anchor [“”], Lightmap [“”], etc…)

Once grabbed, these items will disappear when the trigger is released (can not be added to the physical scene, nor applied to a workspace window, or deleted).

An example in the gifs below:
![ezgif com-optimize 6](https://cloud.githubusercontent.com/assets/25187040/26176332/95b56080-3b0a-11e7-990d-ade07c63e066.gif)
![ezgif com-video-to-gif 14](https://cloud.githubusercontent.com/assets/25187040/26176407/e4df0a4e-3b0a-11e7-9970-f09d95e44a1e.gif)

This seemed like a strange interaction in its current form, thus figured I would make note of it -- and would leave to question whether or not this is an intentional feature (or considered a bug).

**Comment by mtschoen-unity** [comment]
This is a feature. You can only drag/drop the same data type, so numbers to numbers, materials to materials, etc. We should probably document this feature better :)
