### ISSUE TITLE
Free movement sphere + snapping leads to very unexpected behavior

### ISSUE THREAD

**Issue by timoni** [Unity-Technologies/EditorVR#193]
Eg, moving an object slightly pushes it forward and backwards tens of meters. I say cut for now or severely limit how much the object can actually move per degree of controller movement.

**Comment by amirebrahimi** [comment]
Is this at a glancing angle where you are moving something along the horizon?

**Comment by mtschoen-unity** [comment]
So it sounds like the answer here is basically to default "Limit snapping radius" to on
