### ISSUE TITLE
Locomotion arc is doing some pretty, but odd things (Oculus)

### ISSUE THREAD

**Issue by timoni** [Unity-Technologies/EditorVR#196]
When world is scaled, locomotion looks like: https://cl.ly/kWrg It's also nicely animated.

Very low priority but definitely a bug.

**Comment by mtschoen-unity** [comment]
I think the issue was that this wasn't reacting to world scales that were loaded from a previous session. I'm not sure if this is completely resolved, but that issue is addressed in #225

**Comment by amirebrahimi** [comment]
I verified that this exists regardless of previous world scales. You can simply scale the world and try and blink and you should see the issue. Not sure with your locomotion changes.
