### ISSUE TITLE
Workspaces from previous session still in scene but don't follow me

### ISSUE THREAD

**Issue by timoni** [Unity-Technologies/EditorVR#197]
https://cl.ly/kWvU

Here they are after I scaled the world, sitting about three meters above me. They're stuck there; they no longer respect world scaling or my movement.

**Comment by amirebrahimi** [comment]
So, the repro steps are that you?
1. Created workspaces
2. Exit EditorVR
3. Re-enter EditorVR
4. Scale the world
5. Notice that the workspaces don't move with you as you scale the world?

or is it that they are scaled immediately upon re-entering EditorVR?

**Comment by amirebrahimi** [comment]
I just tried those steps above with the latest version and can't repro. If you can record a video or show me in person that would be helpful.
