### ISSUE TITLE
Objects Duplicate When Moving From One MiniWorld Workspace to Another (With Multiple Miniworld Workspaces Open)

### ISSUE THREAD

**Issue by sarahhockman** [Unity-Technologies/EditorVR#234]
**Using EVR-staging and EVR-master [0.0.7]  | Oculus + VIVE | 6/28/17**

In EVR's current state, I'm able to open multiple workspaces at one time -- and in this case, multiple MiniWorlds. This has the potential to be highly useful for a user, for example -- if within a scene with a large map, this gives me the ability to work with multiple viewpoints/areas of my scene at one time. Although this speeds up workflow (along with the features to world-scale the MiniWorld grid and two-handed scale objects), I have noticed a reoccurring issue with **moving objects from one MiniWorld to another.**

Previously, I noticed that I have the ability to drag an object outside of the MiniWorld bounds, which results in the object to appear in my physical scene (at the correct physical scale and placement I dragged it to); along with the ability to drag Assets directly from the project workspace into the MiniWorld SceneView. While there were no noticeable issues with these abilities, I wanted to test the functionality between multiple MiniWorlds. In this test, I had three MiniWorld workspaces open, each focusing on a different perspective of my scene.

Although I am able to move objects from one MiniWorld to another (the object I have selected will translate to the new MiniWorld), a copy of the selected object will appear when my object reaches the new MiniWorld bounds. (This didn't result in any issues in the Console).

**Can be seen in video below:**
https://drive.google.com/file/d/0B25RksN0ueScQmFpVHZVc3hyaDg/view?usp=sharing

**Additionally, an example in this gif:**
![ezgif com-optimize](https://user-images.githubusercontent.com/25187040/27703462-50e7d1bc-5cbc-11e7-8c9a-053c02a2ee81.gif)

The original object remains in the scene where I placed it when moving between MiniWorlds. The duplicates of the objects can be placed throughout the scene (it seems they are legitimately just a copy, and do not affect the original object). In some instances, it appeared that the copy that appeared was the previous object selected.

**Replicate this by:**
1) Open multiple MiniWorld workspaces (2+)
2) Align the MW views to different perspectives of the scene
3) Select and drag an object from one point in a MiniWorld and drag to another MiniWorld Workspace 
4) Objects will duplicate when they are dragged out of the original MiniWord and hit the new MiniWorld workspace bounds.

**Comment by mtschoen-unity** [comment]
Just checked this out with Sarah. It's not duplicating, actually, but just popping into some new location. This happens when you move an object from one MiniWorld to another the second time--the first object you manipulated will be the one to pop.
