### ISSUE TITLE
Duplicate Tooltip appears when hovering objects if BaseActions implement ITooltip

### ISSUE THREAD

**Issue by AndrewTHEManeri** [Unity-Technologies/EditorVR#256]
If any BaseAction (existing or new) implements ITooltip, a duplicate tooltip will appear near the origin when hovering over anything in EVR.

What appears to be happening is that the MultiRayInputModule checks the EVR object and passes this onto the TooltipModule.  It then checks if EVR has a component which implements ITooltip - since EVR contains all the actions as components, this check will return true pretty much all the time if any action implements ITooltip.  From there, it ends up spawning the duplicate tooltip.

**Comment by mtschoen-unity** [comment]
This just came up in my branch, so I've got it.

**Comment by mtschoen-unity** [comment]
We just saw this again in menu-hide, so we'll have to re-visit. "Global Rotation" tooltip was sticking around.

**Comment by mtschoen-unity** [comment]
This was a bug, and has been fixed. The bug we encountered during our EXR sync was different from this one and I'll open a new one for it.
