### ISSUE TITLE
EditorVR is now supported without need of a custom build?

### ISSUE THREAD

**Issue by andybak** [Unity-Technologies/EditorVR#259]
The 2017.2 beta release notes say "EditorVR is now supported without need of a custom build (still requires separate download)."

But when I add the latest Unity package downloaded from https://github.com/Unity-Technologies/EditorVR/releases I get a warning about needing a custom Unity build.

The docs still imply a custom build is needed. It would be useful if they could be updated to explain how to get EditorVR working in the 2017.2 beta.

**Comment by mtschoen-unity** [comment]
Hi there. Well spotted! 

EditorVR mostly works in tbe 2017.2 beta, but there is a UI bug that prevents you from getting any use out of it. This will be fixed shortly, though I'm not sure if it will make it into the next beta. I will reply to this issue as soon as we have working 2017.2 support.

In the meantime, please do go download the experimental 5.6 release and give EVR a try!

**Comment by andybak** [comment]
Any update on the timescale for this?

**Comment by AndrewTHEManeri** [comment]
Look at the milestone coming up...
