### ISSUE TITLE
Blink visuals don't hide when triggered before changing ViewerScale

### ISSUE THREAD

**Issue by dunity** [Unity-Technologies/EditorVR#300]
The blink visuals stay visible (after the blink button is released), and don't perform a blink when the following action is performed:

1: Press & hold the blink button
2: While keeping the blink button held, trigger a two-handed viewerScale action.
3: While performing the viewerScale change, release the held blink button.
4: End the viewerScale action (release both grips).
5: The blink visuals stay visible, and perform no blink action in this case.

**Comment by stella3d** [comment]
repro'd this - looking into fixing tomorrow
