### ISSUE TITLE
Auto-hide main menu when selecting tools that have custom menus

### ISSUE THREAD

**Issue by mtschoen-unity** [Unity-Technologies/EditorVR#302]
The toolflow changes made it so that selecting tools does not auto-hide the main menu. This leads to a confusing behavior for tools that have a custom menu, like the Create Primitive Tool.

We should add a rule in SelectTool that checks if the tool implements IInstantiateMenuUI, and hides the menu if this is the case.

**Comment by dunity** [comment]
The automatic hiding of the main menu can be cumbersome.  Perhaps we can go with a visual, or haptic means of informing the user that there is a secondary menu that was activated (and will be dislayed on hide of mainmenu).  If such a feature is pursued, we could also allow interaction (dip/tap/click/etc) with that visual element to hide the mainmenu, then show the intended toolmenu.
