### ISSUE TITLE
Snapping settings bug: locomotion options are rendering on top of the snapping settings

### ISSUE THREAD

**Issue by timoni** [Unity-Technologies/EditorVR#303]

**Comment by sarahhockman** [comment]
<img width="1417" alt="screen shot 2017-09-28 at 11 09 52 am" src="https://user-images.githubusercontent.com/25187040/30983353-06fff938-a43f-11e7-8a07-8d67631634d9.png">

**#314 --> saw this again in staging[0.0.8]**

It looks like the Settings Pane re-draws over the Snapping settings if the main menu is closed on the Snapping window. 

![ezgif com-optimize 4](https://user-images.githubusercontent.com/25187040/30983411-35e22758-a43f-11e7-82d0-beb002fa734b.gif)


_Replicate this by:_
1) Open Main Menu and navigate to 'Settings' pane
2) Click on Snapping to open snapping settings, then close menu.
3) Click on Unity button to reopen Main Menu, which should open where you left off, on the 'Snapping' pane -- however, the main Settings pane will draw over the snapping settings.

_**You can fix this by clicking on the 'Settings' heading title to re-open the main settings pane.**_
