### ISSUE TITLE
Tooltips

### ISSUE THREAD

**Issue by mtschoen-unity** [Unity-Technologies/EditorVR#32]
We need a way of displaying tooltips throughout the system. A tooltip is a piece of text that will appear when a user hovers over a button. Tooltips will automatically rotate to face the camera, and appear at some position offset relative to the button.

This feature will consist of a ToolTip component which will show/hide the tooltip, and a ToolTipAttribute for specifying tooltip data on dynamically generated UIs.

Because our UI is a mixture of hand-made prefabs and dynamically generated content (i.e. "View All" button on workspaces vs. RadialMenuSlots), there will be two way of defining a Tooltip. On hand-made prefabs, the author will simply add a ToolTip component and set the positional offset as a Vector3 field in the inspector. For dynamically-generated UI, developers will add the ToolTipAttribute with the text string to be displayed. The code which generates these UIs will be modified to check for the ToolTipAttribute and, if present, add a ToolTip component and specify the proper offset based on contect. In this way, the Radial Menu can decide where its ToolTips go based on the position of the button, which could change.

**Comment by timoni** [comment]
- Tooltip angle should be based on initial HMD position, but not billboard.
- On the radial, tooltips should be positioned near the respective action.
- Tooltips should appear at the same time as the rest of the hover states.
- Tooltips should scale in.

**Comment by mtschoen-unity** [comment]
Edit: Tooltips should show up aligned with their target transform, i.e. in the same plane as the Radial menu and aligned with the drag arrows in front of the workspace

**Comment by timoni** [comment]
![tooltips](https://cloud.githubusercontent.com/assets/40673/22170543/c50a07ec-df33-11e6-8ba9-82ee5e360676.png)
