### ISSUE TITLE
Quickly spatial selecting while over a transform manipulator can break the ability to select things

### ISSUE THREAD

**Issue by AndrewTHEManeri** [Unity-Technologies/EditorVR#322]
To Repro - have a few tools open so that spatial selecting can occur.  Choose the selection tool.  Select an object to make the transform manipulator appear.  While the ray is over one of the handles, activate a spatial select as quickly as possible.  If done (in)correctly, most of the manipulators will dissappear - but not all of them - and the ability to select anything is gone.

Sometimes (but not always) this will trigger an error "Gameobject is already being activated or deactivated"  for the handle being manipulated - during the Transform tool's OnSelectionChanged function

**Comment by mtschoen-unity** [comment]
This might be fixed by the annotation PR.

**Comment by mtschoen-unity** [comment]
It is not fixed. I also noticed we can get stuck creating a primitive by spamming spatial select. Not sure if this is more input-related stuff or what. I'll see what I can find.

**Comment by AndrewTHEManeri** [comment]
More consistent repro case even with the spatial select fix-
Select an object
Start dragging one of the transform handles.
Hold down the grip button.  Without letting go of grip, release the trigger.
You'll be in a state where the previously selected transform handle can be seen.
Now trigger a spatial scroll by starting with the grip first, and then trigger.
Switch to a different tool, and you'll get the "Gameobject is already being activated or deactivated"  message.

**Comment by AndrewTHEManeri** [comment]
Further update - doing this same process without being able to spatial select (having no tools in the toolstack) puts the controllers into the previously mentioned locked state.
