### ISSUE TITLE
Prevent ray-based selection of player(head)

### ISSUE THREAD

**Issue by dunity** [Unity-Technologies/EditorVR#351]
Allow only direct-selection of the user's head; don't allow the ray to interact with the player.  Aiming the input-device(controller) at the player's head activates feedback display.

**Comment by mtschoen-unity** [comment]
I looked into this briefly. We should be able to fix this by checking for the head in GetSelectionCandidate as long as it doesn't interfere with grabbing the head in the mini world.  Otherwise we have IGetVRPlayerObjects
