### ISSUE TITLE
Option to disable Selection Tool highlight

### ISSUE THREAD

**Issue by karl-** [Unity-Technologies/EditorVR#36]
Similar to `EditorUtility.SetSelectedWireframeHidden` in the Editor.

The use being custom highlighting schemes.  In my case I want to highlight the mesh triangles and vertices that are being hovered, but not the object as a whole.

As suggested by Amir [here](https://forum.unity3d.com/threads/selection-tool-still-highlights-objects-after-action-is-consumed.450912/) a workaround in the current state is to simply inherit `ISetHighlight` and manually disable the highlight per-object.

**Comment by amirebrahimi** [comment]
@karl-, With 0.0.3 you can now use `ICustomHighlight` to override highlighting for a specific game object. Also, the highlight is now an outline, so it is probably less distracting. You could still return false in your `OnHighlight` after doing your own custom highlight if you would still like to see the default outline.
