### ISSUE TITLE
Multi-select tooltip covers radial menu, and isn't seen on both controllers in selection mode

### ISSUE THREAD

**Issue by dunity** [Unity-Technologies/EditorVR#360]
The tooltip blocks visibility of the radial menu's center region.

In addition, there isn't indication that the mode is enabled on other input-devices/proxies that may be in selection(tool) mode.  This is a UX issue when the mode is enabled via a hand that isn't within view, and the opposite/other hand begins selecting objects (while the user is uninformed of the mode that they're in).

A short-term remedy would be to move the tooltip target location upward(away from the font+top of the controller).  In addition, display the multi-select tooltip on both(all) input-devices/controllers.

A more optimal fix would be the display of the tooltip(stating the user is in multi-select mode), on any controller that is within gaze range.

Side note: The introduction of the "alternate UI" & dynamic controller cursors/pointers may negate the need for a persistent tooltip that is visible.

**Comment by smartberry1122** [comment]
> The tooltip blocks visibility of the radial menu's center region.
> 
> In addition, there isn't indication that the mode is enabled on other input-devices/proxies that may be in selection(tool) mode. This is a UX issue when the mode is enabled via a hand that isn't within view, and the opposite/other hand begins selecting objects (while the user is uninformed of the mode that they're in).
> 
> A short-term remedy would be to move the tooltip target location upward(away from the font+top of the controller). In addition, display the multi-select tooltip on both(all) input-devices/controllers.
> 
> A more optimal fix would be the display of the tooltip(stating the user is in multi-select mode), on any controller that is within gaze range.
> 
> Side note: The introduction of the "alternate UI" & dynamic controller cursors/pointers may negate the need for a persistent tooltip that is visible.



> The tooltip blocks visibility of the radial menu's center region.
> 
> In addition, there isn't indication that the mode is enabled on other input-devices/proxies that may be in selection(tool) mode. This is a UX issue when the mode is enabled via a hand that isn't within view, and the opposite/other hand begins selecting objects (while the user is uninformed of the mode that they're in).
> 
> A short-term remedy would be to move the tooltip target location upward(away from the font+top of the controller). In addition, display the multi-select tooltip on both(all) input-devices/controllers.
> 
> A more optimal fix would be the display of the tooltip(stating the user is in multi-select mode), on any controller that is within gaze range.
> 
> Side note: The introduction of the "alternate UI" & dynamic controller cursors/pointers may negate the need for a persistent tooltip that is visible.



> The tooltip blocks visibility of the radial menu's center region.
> 
> In addition, there isn't indication that the mode is enabled on other input-devices/proxies that may be in selection(tool) mode. This is a UX issue when the mode is enabled via a hand that isn't within view, and the opposite/other hand begins selecting objects (while the user is uninformed of the mode that they're in).
> 
> A short-term remedy would be to move the tooltip target location upward(away from the font+top of the controller). In addition, display the multi-select tooltip on both(all) input-devices/controllers.
> 
> A more optimal fix would be the display of the tooltip(stating the user is in multi-select mode), on any controller that is within gaze range.
> 
> Side note: The introduction of the "alternate UI" & dynamic controller cursors/pointers may negate the need for a persistent tooltip that is visible.
