### ISSUE TITLE
Plane flickers in MiniWorld

### ISSUE THREAD

**Issue by DennisDeRykeUnity** [Unity-Technologies/EditorVR#37]
I have a plane in my scene.  In the MiniWorld workspace the plane has a flickering effect as shown in the attached screen shot.  This is not a big problem but it is a bit distracting.  

The flickering is probably due to highlighting that occurs when the selection ray from one of the hand controllers intersects with the non-MiniWorld plane.

![flickerplane](https://cloud.githubusercontent.com/assets/22460837/21947454/251feeca-d99a-11e6-8f90-9c51d3b5cdd0.png)

**Comment by mtschoen-unity** [comment]
Closing this. Not an issue with new highlights
