### ISSUE TITLE
MainMenu sub-face/custom buttons lacking haptics

### ISSUE THREAD

**Issue by dunity** [Unity-Technologies/EditorVR#383]
Custom main menu sub-face-buttons (snapping, locomotion, etc), are lacking the standard haptic(s) implementation.  These buttons should implement the same haptics for hover/etc as that of the standard main menu buttons (tools, workspaces, etc).

**Comment by stella3d** [comment]
i'll grab this one, i haven't implemented any haptics yet and would love to
