### ISSUE TITLE
Inconsistent selection level of object in hierarchy

### ISSUE THREAD

**Issue by DennisDeRykeUnity** [Unity-Technologies/EditorVR#40]
See the attached screen shots.  In EditorVR if I use raycast selection to select PurpleCube it actually selects PurpleArmy which is two layers up in the hierarchy.  But if I raycast select a GreenTank it selects GreenTanks which is only one layer up in the hierachy.  Selecting a BrownTank gets BrownTanks, also one level up.  

Does the hierachy level which is selected via raycast depend on whether or not the hierarchy contains prefabs versus only non-perfab GameObjects? 

![inconsistenthierarchy](https://cloud.githubusercontent.com/assets/22460837/21948606/1037005a-d9a1-11e6-9f7d-b33e23c53eed.png)

**Comment by amirebrahimi** [comment]
@mtschoen-unity - this was related to the root select we used to have, right? I think this bug is invalid now.

**Comment by mtschoen-unity** [comment]
Yep. That would have caused it, and it has been removed.
