### ISSUE TITLE
Inconsistent hierarchy with direct versus raycast selection

### ISSUE THREAD

**Issue by DennisDeRykeUnity** [Unity-Technologies/EditorVR#41]
I get a different selection level in the hierarchy depending on whether I use direct selection versus raycast selection.  One of the screenshots shows direct selection of the right front wheel of GreenTank1, which results in the GreenTank1 prefab being selected as shown in the Hierarchy view.  In the EditorVR window you can see that GreenTank2 is not selected.  

I de-selected, then used raycast selection on the same wheem of the same tank.  As shown in the other screenshot, this results in the GreenTanks transform being selected in the Hierarchy view, and the EditorVR window shows that GreenTank2 is selected.  

![direct](https://cloud.githubusercontent.com/assets/22460837/21949991/763e30b2-d9ab-11e6-8dcf-b8ad226fdb3f.png)

![raycast](https://cloud.githubusercontent.com/assets/22460837/21949994/78925a1e-d9ab-11e6-9739-3749d01b4bc0.png)

**Comment by amirebrahimi** [comment]
Sames issue as #40
