### ISSUE TITLE
"You can't start EditorXR without at least one context"

### ISSUE THREAD

**Issue by andybak** [Unity-Technologies/EditorVR#428]
Using Unity 2017.3.0b9 and a fresh clone of the development branch.

Full error: Exception: You can't start EditorXR without at least one context. Try re-importing the package or use version control to restore the default context asset

I tried creating a new EditorVR Cintext. I wasn't sure what it wanted adding to the "Default Tool Stack" array so I added a few scripts that ended with the word "Tool". (TransformTool etc)

Didn't seem to work. The error went away but I couldn't do anything in the EditorVR view.

**Comment by mtschoen-unity** [comment]
Well that's not good! I'm going to see if I can reproduce your issue, but my guess is that somehow the main EditorVR context got borked in the clone. Either it failed to check out completely, or some issue caused Unity to overwrite it with garbage.

I don't think this would cause the issue, but do you have LFS installed? If not, you need it. If so, can you try a git lfs pull in the EditorVR folder to see if you're missing some LFS assets?

**Comment by mtschoen-unity** [comment]
I just tried a fresh clone in b9, and did not have this issue.  Does this file exist in your project?

https://github.com/Unity-Technologies/EditorVR/blob/development/Scripts/Core/Contexts/EditorVR.asset

And is it set as the Default context in EditingContextManager, above?

**Comment by andybak** [comment]
I'm an idiot. I'd originally done the LFS stuff but for some reason later did a fresh checkout as just a normal git clone.

**Comment by mtschoen-unity** [comment]
Haha no worries! Thanks for following up. Happy Thanksgiving!
