### ISSUE TITLE
Presentation camera shouldn't take into account the previous-disabled rotation when enabled

### ISSUE THREAD

**Issue by dunity** [Unity-Technologies/EditorVR#441]
Currently, when enabling the presentation camera (VRSmoothCamera), there can be a moment of very quick rotation that looks distracting.  When apparent, this results in an odd looking, untended rotation (based on the rotation delta from the previous m_Rotation that was lerped in LateUpdate()).  The roll rotation correction between the VRCamera & the VRSmoothCamera is to be expected when toggling this setting, but this odd correction/lerp of the previous m_Rotation value should not be present.

**Comment by mtschoen-unity** [comment]
Fixed by #442
