### ISSUE TITLE
Drag and drop to re-arrange hierarchy

### ISSUE THREAD

**Issue by mtschoen-unity** [Unity-Technologies/EditorVR#46]
Like the 2D Hierarchy window, we should be able to drag and drop objects to change their order and parenting.

**Comment by timoni** [comment]
**Change double-click to long hold to select.**
To avoid conflicting with the slide-to-change-value in the Inspector:

- Add time-based hover visuals to indicate when object begins, then is, selected.
- Include 'tear' feel: controller must move a certain amount of distance away from the workspace before the object is considered selected.
- Change angle of list item when attached to the controller. Should initially face user's HMD position,  but should not billboard; instead, should remain consistently attached to controller.

**Comment by mtschoen-unity** [comment]
Time/distance based "tear off" will be tasked for a separate feature (and apply to Inspector fields).

This feature is mostly done in improvements/schoen/hierarchy-drag-drop. After design review with @timoni, we will add animation feedback when dropping a field so that you see where it went.

**Comment by mtschoen-unity** [comment]
We discussed including an "alt-click" to expand/collapse all children when clicking a foldout arrow. My suggestion is using the grip trigger while clicking the regular trigger. @timoni, thoughts on button mapping?
