### ISSUE TITLE
2 hands interactions

### ISSUE THREAD

**Issue by j2l** [Unity-Technologies/EditorVR#5]
Here's what I found:
I can build a wall by starting a freeform cuboid with one hand and slide (touchpad) to another location with the other, very convenient! 

But I can also select an axis to slide an object with one hand and, at the same time, select the clone in the menu (rotating thumb on the Vive touchpad) with other hand, but it does nothing. 
It should equal "clone it and move the copy" (like sketchup ctrl+move).

It opens a whole world of natural interactions!

Heres a screenshot where left hand select menu while right hand is on blue axis to move pillar:
![capture](https://cloud.githubusercontent.com/assets/65325/21460343/5a59a97c-c947-11e6-9d89-44e265a92e57.PNG)

**Comment by amirebrahimi** [comment]
@j2l - coming back to this as I think it might be fixed. Were you wanting the cloned object to be selected by default after cloning or were you referring to something else?

**Comment by j2l** [comment]
Selected and pasted in place.
Thanks

**Comment by amirebrahimi** [comment]
In that case, I believe this is fixed by #186, which will show up in 0.0.8. When that releases, try it out or try it out now if you like by pulling development. Re-open the ticket if we haven't addressed your concern.
