### ISSUE TITLE
Allow for swapping multiple Locomotion Tools

### ISSUE THREAD

**Issue by Mvivant** [Unity-Technologies/EditorVR#85]
Hi, 
I need help , I want to create a new locomotion tool with a new device (3dRudder controller)

The commit with all sources: https://github.com/Mvivant/EditorVR/commit/b82e9cd9f200ae49efe3e788e96676b3a245ef67

But it doesn't work, I copy/paste the code of BlinkLocomotion and I changed ICustomActionMap by IStandardActionMap (because in Debug I see my ActionMap is null), but my ProcessInput function is never called. Why ? I missing something ?

What is the flow to create a new tool for locomotion (for exemple to move the cameraRig with the gamepad) ?

Thanks

**Comment by mtschoen-unity** [comment]
Hi, thanks for trying EditorVR and sharing your code. Unfortunately, you've stumbled upon a missing future feature.

Right now, we set up and update our BlinkLocomotionTool manually in EditorVR. You're probably better off modifying BlinkLocomotionTool directly for the time being.  We will eventually do something along the lines of enumerating all classes that implement ILocomotor and adding them to a settings menu.

I've edited your issue title slightly and marked it as an improvement, so that we can refer back to it when we implement this feature.

**Comment by amirebrahimi** [comment]
@Mvivant - have you tried replacing the locomotion tool via EditingContexts? There's a default one that you can copy and configure located at Scripts/Core/Contexts/EditorVR.asset.

**Comment by Mvivant** [comment]
@amirebrahimi  - I added my locomotion tool via EditingContexts, my function ProcessInput is called thanks, but it's not called by my CustomActionMap (3dRudder).
I see an [serialized]ActionMap variable in my tool, but there are only getter, how do I set this variable ? Is automatic ?

**Comment by mtschoen-unity** [comment]
If everything is working properly, you should be able to cast the ActionMapInput argument of ProcessInput to the corresponding AMI for your ActionMap.  You are intended to expose your ActionMap to the system via CustomActionMap.
Generally, you introduce a serialized field that you can use to set the ActionMap ScriptableObject on your script, and then implement the actionMap getter property to return that object. The system will create your ActionMapInput for you, put it into the PlayerHandle, and give you access to it via ProcessInput.

Check out VacuumTool for the simplest example of this.

**Comment by Mvivant** [comment]
Yes but the issue is with my new device input, I think tool react only with VRInputDevice
I tested to change VRInputDevice by Keyboard or Mouse and it doesn't work...
Is it hardcoded somewhere to use only VRInputDevice?

**Comment by AndrewTHEManeri** [comment]
You need to create your D3dRudderInputToEvents component.

Try doing it in libs\input-prototype\Input\Core\InputSystem.cs around line 26 and see if that gets things working for you.

I understand that's not the best place to do things in a plug-in sense, but if that works it tells us where we need to add another hook for EVR

**Comment by Mvivant** [comment]
It doesn't work, I have this error now
```
NullReferenceException: Object reference not set to an instance of an object
UnityEditor.Experimental.EditorVR.Utilities.InputUtils.CollectDeviceSlotsFromActionMapInput (UnityEngine.InputNew.ActionMapInput actionMapInput, System.Collections.Generic.HashSet`1& deviceSlots) (at Assets/EditorVR/Scripts/Utilities/InputUtils.cs:41)
UnityEditor.Experimental.EditorVR.Core.EditorVR+Tools.SpawnTool (System.Type toolType, System.Collections.Generic.HashSet`1& usedDevices, UnityEngine.InputNew.InputDevice device) (at Assets/EditorVR/Scripts/Core/EditorVR.Tools.cs:165)
UnityEditor.Experimental.EditorVR.Core.EditorVR+Tools.SpawnDefaultTools (IProxy proxy) (at Assets/EditorVR/Scripts/Core/EditorVR.Tools.cs:102)
UnityEditor.Experimental.EditorVR.Core.EditorVR+Rays.OnProxyActiveChanged (IProxy proxy) (at Assets/EditorVR/Scripts/Core/EditorVR.Rays.cs:279)
UnityEditor.Experimental.EditorVR.Core.EditorVR+Rays+<CreateAllProxies>c__AnonStorey2.<>m__0 () (at Assets/EditorVR/Scripts/Core/EditorVR.Rays.cs:157)
UnityEditor.Experimental.EditorVR.Input.BaseInputToEvents.set_active (Boolean value) (at Assets/EditorVR/Scripts/Input/BaseInputToEvents.cs:19)
UnityEditor.Experimental.EditorVR.Input.ViveInputToEvents.Update () (at Assets/EditorVR/Scripts/Input/ViveInputToEvents.cs:95)
```

It's here
```
public static void CollectDeviceSlotsFromActionMapInput(ActionMapInput actionMapInput, ref HashSet<DeviceSlot> deviceSlots)
{
	foreach (var deviceSlot in actionMapInput.controlScheme.deviceSlots)
	{
		deviceSlots.Add(deviceSlot);
	}
}
```
The controlScheme is null but in Inspector I have a controlScheme on my Locomotion3dRudder.
Do you have an idea?

**Comment by mtschoen-unity** [comment]
This sounds like a bug in the input prototype. Could you share your code somehow? Maybe fork EVR and commit your changes to a branch? We might be able to just fix the ActionMap, but it will require some poking around in the debugger.

**Comment by Mvivant** [comment]
Yes look my commit on the 3dRudder branch : https://github.com/Mvivant/EditorVR/commit/36059f24199d0f588fc25bb8801e4e3b03e5498d

I succeeded to move the cameraRig with the 3dRudderTool with this changes:
* Add new enum Middle in Node.cs and DeviceModuleInput.cs
* Remove filter for other device than VRInputDevice in DeviceModuleInput.GetSystemDevice()  
* Comment the if(m_Preferences.blinkMode) in LocomotionTool.cs because it do an error, but you can remove this comment.
* Add the 3dRudder device in Input/Core/InputDeviceManager.cs line 46
```
var rudder = new D3dRudder(); 
RegisterDevice(rudder); 
```

It works but it's not like I want, it doesn't work as a plugin.
What the procedure to do this ?

**Comment by mtschoen-unity** [comment]
Sorry for the delay; I finally got a chance to look at this. You are right that you can't get this done without modifying the input prototype. However, rather than hardcoding the new D3DRudder device in InputDeviceManager, I was able to avoid the null reference by simply adding

**Comment by AndrewTHEManeri** [comment]
That seems like a reasonable extension for the inputsystem - I'll mark it down as something to add into EVR
