### ISSUE TITLE
Flicking Objects + Gizmo

### ISSUE THREAD

**Issue by sarahhockman** [Unity-Technologies/EditorVR#89]
[ **#78**, Using EVR-staging, 10 March 2017 ]:

When manipulating a scene, it was frequent that several objects would disappear from view, but I if moved closer/further away, the objects would re-appear, but then flicker or vanish.

_This instance seen in gif below:_ 

![ezgif com-crop 1](https://cloud.githubusercontent.com/assets/25187040/23806772/dffbef92-0577-11e7-87d9-ed22f5fff332.gif)

Additionally, similarly to above, there are instances where I have an object selected, but when I move my cursor/raycast about the scene, then the gizmo will flicker. 

![ezgif com-crop 3](https://cloud.githubusercontent.com/assets/25187040/23807178/96b42406-0579-11e7-8c54-712014a5d00b.gif)

**Comment by mtschoen-unity** [comment]
This scene has occlusion culling data. The fix is to turn off occlusion culling on the VR camera. I think this is safe to do across the board. I'll be making a PR for this fix now.

**Comment by sarahhockman** [comment]
[[ Confirmed // Approved ]]

_Using EVR-staging on 3-14-17, unable to replicate this instance_
