### ISSUE TITLE
Allow scaling of the world from viewer's perspective

### ISSUE THREAD

**Issue by amirebrahimi** [Unity-Technologies/EditorVR#9]
Currently it's only possible to have 1:1 scale from the viewer's perspective. We have the MiniWorld to allow scaling the view of the scene for manipulation purposes. This feature would allow scaling the view of the world around you.

**Comment by koreldan** [comment]
yep, agree.

A scaling function that lets to scale the enviroment using both grip buttons like 'Universe Sandbox ² ' would be great... maybe also easy to implement
