### ISSUE TITLE
Tiny Keyboard (Inspector)

### ISSUE THREAD

**Issue by sarahhockman** [Unity-Technologies/EditorVR#98]
[#99, _Using EVR-development, pulled 20 March 2017_]

I noticed that when attempting to manipulate an object via the Inspector workspace, and clicking on the numerical value/white box, the keyboard appears at a very small scale.

In the instance I first noticed this, I had re-scaled the workspace to 100.00 then again to 10.00. In both cases, when revisiting the Inspector, the tiny keyboard reappeared.

I then rescaled to 1.00/default perspective, and had the same result. 

![ezgif com-crop](https://cloud.githubusercontent.com/assets/25187040/24124812/b106b04c-0d82-11e7-860b-c1518a261868.gif)
_Scale is default/1.00, prompted with tiny keyboard in Inspector._

![ezgif com-optimize 2](https://cloud.githubusercontent.com/assets/25187040/24124817/b686c566-0d82-11e7-9d3a-a33d53b976b7.gif)
_Scale is 10.00, still at tiny keyboard appears via inspector._ 

[_Note: I'll revisit this in EVR-staging as well._]

**Comment by mtschoen-unity** [comment]
Good catch. We'll need to apply viewer scaling to the keyboard. It will almost definitely happen in staging, as well.

**Comment by sarahhockman** [comment]
Same result with both branches: 

_git.exe checkout bugfixes/schoen/keyboard-fix --
Your branch is up-to-date with 'origin/bugfixes/schoen/keyboard-fix'.
Already on 'bugfixes/schoen/keyboard-fix'
Success (63 ms @ 3/21/2017 2:38:45 PM)_

_git.exe checkout remotes/origin/staging --
Success (78 ms @ 3/21/2017 2:41:35 PM)_

I think we're close; the only way to replicate the keyboard bug is:
1) Open EVR, immediately re-scale the player/world (I tried both 10.00 and 100.00).
2) Select an object --> open Inspector --> open keyboard --> small keyboard appears
3) It looks like keyboard scale is based on the world/player scale upon first opening; the keyboard then remains that scale for the duration of the session. 

_(i.e. If keyboard is open while player is scaled at 1.0, keyboard remains proper scale. But, if player re-scales to larger/10.00/10.00 ect., then prompts for keyboard, it will appear at the smaller scale and remains tiny for the duration of the session.)_

**Comment by sarahhockman** [comment]
^^^
Issue resolved -- no longer experiencing issue // unable to replicate
